security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret2
      scope: read,write
      auto-approve-scopes: '.*'

spring:
  security:
    user:
      name: user
      password: password
      roles: BASIC_AUTH